### ISSUE TITLE
"imported [file] with no plugin"

### ISSUE THREAD

**Issue by MarjaE2** [GenjiApp/EPUB-Plugins#1]
A quick test run with mdimport -t -d 3 [file] shows that, even after running mdimport -r /Users/[Name]/Library/Spotlight/EPUB.mdimporter, MacOS Mojave fails to use the plugins.

**Comment by GenjiApp** [comment]
I signed MDImporter. Please try it.
https://github.com/GenjiApp/EPUB-Plugins/releases/tag/mdimporter_v1.0.1_signed

**Comment by MarjaE2** [comment]
Thank you, it seems to run.
