### ISSUE TITLE
EPUB.qlgenerator Catalina Compatibility

### ISSUE THREAD

**Issue by bobodoll131** [GenjiApp/EPUB-Plugins#3]
Hi, been using this since the Sierra days, but after upgrading my machine to Catalina the system no longer seems to recognize your plugin. I've copied the plugin to both ~/ and / Libraries, but can't seem to get it to work. Neither 1.1.1 or 1.1.2 allows me to preview the epub file's text via quicklook. Even after removing quarantine and entering qlmanage -r in terminal, I just get the basic info window with file name, size and modified date. No contents are rendered.

Is there something I'm doing wrong?

**Comment by GenjiApp** [comment]
v1.1.2 is fixed this issue. However, v1.1.2 supports macOS Monterey or later only.
Upgrade your Mac to Monterey, if you can.
I can't fix this issue for Catalina, because I'm no longer have a Catalina Mac machine.
