### ISSUE TITLE
Submit to Homebrew

### ISSUE THREAD

**Issue by huyz** [GenjiApp/EPUB-Plugins#4]
Would be nice to replace the outdated https://github.com/jaketmp/ePub-quicklook (formula: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/epubquicklook.rb) with this repo instead.

**Comment by GenjiApp** [comment]
I'm not using Homebrew.

**Comment by huyz** [comment]
Ok but tons of other macOS users do. Makes installation a lot easier.

I'll try to figure how to submit it myself.
