### ISSUE TITLE
about 1MB HTML preview limit in Quick Look generator 

### ISSUE THREAD

**Issue by HaveF** [GenjiApp/EPUB-Plugins#5]
Hi, Genji,

Great thanks for this plugins,

This plugins works great with foxtrot search (https://help.foxtrot-search.com/650-third-party-file-formats). 

The foxtrot heavily relay on the Quick Look plugins to display epub's content.

So, the only problem I faced now is,  when the epub is great than 1MB, I cannot easily view the content by your Quick Look plugins.

Could it possible to release a bigger preview size limit version of quick look plugins?

Thanks again.

**Comment by GenjiApp** [comment]
If you are familiar with Objective-C, edit [line 21 in `Quick Look Generator/GeneratePreviewForURL.m`](https://github.com/GenjiApp/EPUB-Plugins/blob/master/Quick%20Look%20Generator/GeneratePreviewForURL.m#L21).

from:
`static const NSUInteger kMaxLenghOfContents = 1024 * 1024;`

to:
`static const NSUInteger kMaxLenghOfContents = 1024 * 1024 * 10;` // about 10MB

And, build Quick Look plugin yourself.

**Comment by HaveF** [comment]
That's all?

I'm not familiar with OC, but I will try to build. Thanks!

**Comment by GenjiApp** [comment]
EPUB.qlgenerator v1.2 is out. Please check it.

**Comment by GenjiApp** [comment]
Oops, the feature of changing the loading limit may not work properly. I will investigate.

**Comment by GenjiApp** [comment]
I changed QLGenerator's loading limit from 1MB to 50MB. Please check it.

**Comment by HaveF** [comment]
Works like charm ❤️ ❤️ ❤️ Thanks
