### ISSUE TITLE
 changing the size of the preview window 

### ISSUE THREAD

**Issue by goodoldtime** [GenjiApp/EPUB-Plugins#6]
I tried to change Quick Look preview size by increasing the value of QLPreviewHeight and QLPreviewWidth in Info.plist of EPUB.qlgenerator. It works, but after booting EPUB.qlgenerator stops working completely. I want the size of the preview window to be bigger without using the mouse. Any idea how to solve this?

**Comment by GenjiApp** [comment]
The plugins are signed with a Developer ID, which verifies whether an app has been modified by anyone. If you edit the Info.plist file, macOS will recognize the app as modified and block its launch.

One of the proper solution is to build the plugin yourself and sign it with your Developer ID.
