### ISSUE TITLE
Please consider purchasing "Murasaki", an EPUB Reader app I developed. It's on the Mac App Store. It includes a Quick Look Extension that is compatible with macOS Sequoia.

### ISSUE THREAD

**Issue by steveparry1** [GenjiApp/EPUB-Plugins#8]
Please consider purchasing "Murasaki", an EPUB Reader app I developed. It's on the Mac App Store. It includes a Quick Look Extension that is compatible with macOS Sequoia.

_Originally posted by @GenjiApp in https://github.com/GenjiApp/EPUB-Plugins/issues/7#issuecomment-2380616863_

**Comment by steveparry1** [comment]
I just bought the Murasaki app... When using the Quicklook preview in a few epubs I can scroll to the end of the book. But on most I can only scroll the first few pages... Also the Contents listing is shown but when I click on a chapter nothing happens. These limitations are a disappointment and not mentioned in your description.

**Comment by GenjiApp** [comment]
1. Launch Murasaki
2. Open Settings
3. Select "Quick Look" pane
4. Increase "Loading Data Size Limit" slider

**Comment by steveparry1** [comment]
Thank you, that helps a lot in seeing much more of the preview. I guess the fact that links don't work in Quicklook is normal?

**Comment by GenjiApp** [comment]
> I guess the fact that links don't work in Quicklook is normal?

It is by design the same as before.
